### ISSUE TITLE
[React/Redux] Réimplémenter Redux pour comprendre la lib

### ISSUE THREAD

**Issue by sutter** [Alqemist-labs/technical_itches#6]
Redux est une libraire de gestion de state, souvent utilisée avec React (mais pas que !!).

La lib est très simple, et peut se réimplémenter en quelques dizaines de lignes de code.
L'idée du workshop est d'en expliquer le fonctionnement, et de voir comment réimplémenter la librairie facilement, pour mieux la comprendre.

**Comment by clementoriol** [comment]
(Update de la desc)

**Comment by clementoriol** [comment]
Ce workshop pourrait être suivi, à une autre session, par https://github.com/Alqemist-labs/technical_itches/issues/7 qui explique comment branche Redux à React
